# Generated by Django 2.0.2 on 2018-02-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='价格'),
        ),
    ]
